language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

virtualenv:
  system_site_packages: true

install:
  - pip install virgil-crypto

script:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; python -m unittest discover virgil_crypto.tests -p "*_test.py"
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; python -m unittest discover virgil_crypto.tests -p "*_test.py"
  - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; python -m unittest discover virgil_crypto.tests -p "*_test.py"
  - if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; python -m unittest discover virgil_crypto.tests -p "*_test.py"
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; python -m unittest discover virgil_crypto.tests -p "*_test.py"
  - if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; python -m unittest discover virgil_crypto.tests -p "*_test.py"

notifications:
  email:
  - const_ant_in@virgilsecurity.com