os: linux

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

env:
  global:
    - REPO=VirgilSecurity/virgil-sdk-python
    - GIT_TAG=$TRAVIS_TAG
    - GIT_COMMIT=$TRAVIS_COMMIT
    - GIT_BRANCH=$TRAVIS_BRANCH
    - OS_NAME=$(echo $TRAVIS_OS_NAME)

matrix:
  include:
    - os: osx
      language: generic
      env: PYTHON=2.7.15 PYTHON_VERSION=2.7 OS_NAME=darwin
    - os: osx
      language: generic
      env: PYTHON=3.4.9 PYTHON_VERSION=3.4 OS_NAME=darwin
    - os: osx
      language: generic
      env: PYTHON=3.5.6 PYTHON_VERSION=3.5 OS_NAME=darwin
    - os: osx
      language: generic
      env: PYTHON=3.6.7 PYTHON_VERSION=3.6 OS_NAME=darwin
    - os: osx
      language: generic
      env: PYTHON=3.7.1 PYTHON_VERSION=3.7 OS_NAME=darwin
    - os: windows
      language: shell
      before_install:
        - choco install python2
        - python -m pip install --upgrade pip
      env: PATH=/c/Python27:/c/Python27/Scripts:$PATH
    - os: windows
      language: shell
      before_install:
        - choco install python --version 3.5.4
        - python -m pip install --upgrade pip
      env: PATH=/c/Python35:/c/Python35/Scripts:$PATH
    - os: windows
      language: shell
      before_install:
        - choco install python --version 3.6.7
        - python -m pip install --upgrade pip
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
    - os: windows
      language: shell
      before_install:
        - choco install python --version 3.7.2
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH


before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update
    brew install openssl readline
    brew outdated pyenv || brew upgrade pyenv
    brew install pyenv-virtualenv
    pyenv install $PYTHON
    export PYENV_VERSION=$PYTHON
    export PATH="/Users/travis/.pyenv/shims:${PATH}"
    pyenv-virtualenv venv
    source venv/bin/activate
  fi
  python --version

install:
  - pip install virgil-crypto-lib || pip3 install virgil-crypto-lib
  - pip install . || pip3 install .

script:
  - pwd
  - python -m unittest discover -s virgil_crypto/tests -p "*_test.py"

after_success: |
  if [[ $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
    make docs
  fi


deploy:
  # Upload docs to gh-pages
  - provider: pages
    skip_cleanup: true
    github-token: $GITHUB_ACCESS_TOKEN
    local_dir: "docs"
    on:
      repo: $REPO
      tags: true
      condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+

notifications:
  email:
  - const_ant_in@virgilsecurity.com