os: linux

language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

env:
  global:
    - CDN_ARTIFACTS=$([ "$TRAVIS_BRANCH" == "master" ] && echo "virgil-crypto" || echo "virgil-crypto-dev")
    - OS_NAME=$(echo $TRAVIS_OS_NAME)
    - PYTHON_VERSION=$(echo "$TRAVIS_PYTHON_VERSION" | sed -e 's/-dev//g')

matrix:
  include:
    - os: osx
      language: generic
      env: PYTHON=2.7.15 PYTHON_VERSION=2.7 OS_NAME=darwin
    - os: osx
      language: generic
      env: PYTHON=3.3.7 PYTHON_VERSION=3.3 OS_NAME=darwin
    - os: osx
      language: generic
      env: PYTHON=3.4.9 PYTHON_VERSION=3.4 OS_NAME=darwin
    - os: osx
      language: generic
      env: PYTHON=3.5.6 PYTHON_VERSION=3.5 OS_NAME=darwin
    - os: osx
      language: generic
      env: PYTHON=3.6.7 PYTHON_VERSION=3.6 OS_NAME=darwin
    - os: osx
      language: generic
      env: PYTHON=3.7.1 PYTHON_VERSION=3.7 OS_NAME=darwin

before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update
    brew install openssl readline
    brew outdated pyenv || brew upgrade pyenv
    brew install pyenv-virtualenv
    pyenv install $PYTHON
    export PYENV_VERSION=$PYTHON
    export PATH="/Users/travis/.pyenv/shims:${PATH}"
    pyenv-virtualenv venv
    source venv/bin/activate
    python --version
  fi

install:
  - echo $CDN_ARTIFACTS
  - echo $TRAVIS_PYTHON_VERSION
  - echo $PYTHON_VERSION
  - wget https://cdn.virgilsecurity.com/$CDN_ARTIFACTS/VERSION
  - sed -i -e 's/-dev//g' VERSION
  - echo "virgil-crypto-$(cat VERSION)-python-${PYTHON_VERSION}-${OS_NAME}-*x86_64.tgz"
  - wget -np -nd -r https://cdn.virgilsecurity.com/$CDN_ARTIFACTS/python/ -A "virgil-crypto-$(cat VERSION)-python-${PYTHON_VERSION}-${OS_NAME}-*x86_64.tgz"
  - cd virgil_crypto && tar xzf ../*.tgz --strip=2
  - ls -la
  - cd ..

script:
  - pwd
  - python -m unittest discover -s virgil_crypto/tests -p "*_test.py"

notifications:
  email:
  - const_ant_in@virgilsecurity.com