os:
  - linux
  - osx

language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - wget https://cdn.virgilsecurity.com/virgil-crypto-dev/VERSION
  - export OS_NAME=name=$([ "$TRAVIS_OS_NAME" == "osx" ] && echo "darwin" || echo ${TRAVIS_OS_NAME})
  - wget -np -nd -r https://cdn.virgilsecurity.com/virgil-crypto-dev/python/ -A "virgil-crypto-$(cat VERSION)-python-${TRAVIS_PYTHON_VERSION}-${OS_NAME}-x86_64.tgz"
  - cd virgil_crypto && tar xzf ../*.tgz --strip=2 --wildcards "*.py" "*.so" -C virgil_crypto/

script:
  - cd virgil_crypto && python -m unittest discover -p "*_test.py"

notifications:
  email:
  - const_ant_in@virgilsecurity.com