os:
  - linux
  - osx

language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

env:
  global:
    - CDN_ARTIFACTS=$([ "$TRAVIS_BRANCH" == "master" ] && echo "virgil-crypto" || echo "virgil-crypto-dev")
    - OS_NAME=$([ "$TRAVIS_OS_NAME" == "osx" ] && echo "darwin" || echo ${TRAVIS_OS_NAME})

install:
  - wget https://cdn.virgilsecurity.com/$CDN_ARTIFACTS/VERSION
  - sed -i -e 's/-dev//g' VERSION
  - echo "virgil-crypto-$(cat VERSION)-python-${TRAVIS_PYTHON_VERSION}-${OS_NAME}-x86_64.tgz"
  - wget -np -nd -r https://cdn.virgilsecurity.com/$CDN_ARTIFACTS/python/ -A "virgil-crypto-$(cat VERSION)-python-${TRAVIS_PYTHON_VERSION}-${OS_NAME}-x86_64.tgz"
  - cd virgil_crypto && tar xzf ../*.tgz --strip=2 --wildcards "*.py" "*.so"
  - ls -la
  - cd ..

script:
  - pwd
  - python -m unittest discover -s virgil_crypto/tests -p "*_test.py"

notifications:
  email:
  - const_ant_in@virgilsecurity.com